# Step 1: Set the base image
FROM node:18-alpine as build

# Step 2: Set working directory
WORKDIR /app

# Step 3: Install dependencies
COPY package.json yarn.lock ./

# Step 4: Copy the monorepo (except the ignored files)
COPY . .

# Step 5: Install dependencies using Yarn
RUN yarn install --frozen-lockfile

# Step 6: Build the React app
RUN yarn workspace helloreactjswithvite build

# Step 7: use port 3000
EXPOSE 3000

# Step 8: run the command line below after the container spins up
# not part of the image creation process
CMD [ "yarn", "workspace", "helloreactjswithvite", "preview" ]