# Delete the task role resource
# - op: remove
#   path: /Resources/TaskRole

# Add a service connect alias
# - op: add
#   path: /Resources/Service/Properties/ServiceConnectConfiguration/Services/0/ClientAliases/-
#   value:
#     Port: !Ref TargetPort
#     DnsName: yamlpatchiscool

# Replace the task role in the task definition
# - op: replace
#   path: /Resources/TaskDefinition/Properties/TaskRoleArn
#   value: arn:aws:iam::123456789012:role/MyTaskRole

Resources:
  ScheduledScaleDownNight:
    Type: AWS::ApplicationAutoScaling::ScheduledAction
    Properties:
      ScheduledActionName: ScaleDownWeeknights
      ServiceNamespace: ecs
      ResourceId: !Sub "service/mymonorepo-app-trial-1-production-Cluster-8aYgoWUVqGeI/mymonorepo-app-trial-1-production-mymonorepo-svc-lb-hello-next-js-trial-1-prod-Service-EAsQ9ulL2MMR"
      ScalableDimension: ecs:service:DesiredCount
      Schedule: "cron(0 11 ? * MON-FRI *)"
      ScalableTargetAction:
        MinCapacity: 0
        MaxCapacity: 0

  ScheduledScaleDownWeekend:
    Type: AWS::ApplicationAutoScaling::ScheduledAction
    Properties:
      ScheduledActionName: ScaleDownWeekend
      ServiceNamespace: ecs
      ResourceId: !Sub "service/mymonorepo-app-trial-1-production-Cluster-8aYgoWUVqGeI/mymonorepo-app-trial-1-production-mymonorepo-svc-lb-hello-next-js-trial-1-prod-Service-EAsQ9ulL2MMR"
      ScalableDimension: ecs:service:DesiredCount
      Schedule: "cron(0 0 ? * SAT,SUN *)"
      ScalableTargetAction:
        MinCapacity: 0
        MaxCapacity: 0

  ScheduledScaleUpWeekdays:
    Type: AWS::ApplicationAutoScaling::ScheduledAction
    Properties:
      ScheduledActionName: ScaleUpWeekdays
      ServiceNamespace: ecs
      ResourceId: !Sub "service/mymonorepo-app-trial-1-production-Cluster-8aYgoWUVqGeI/mymonorepo-app-trial-1-production-mymonorepo-svc-lb-hello-next-js-trial-1-prod-Service-EAsQ9ulL2MMR"
      ScalableDimension: ecs:service:DesiredCount
      Schedule: "cron(0 23 ? * SUN-THU *)"
      ScalableTargetAction:
        MinCapacity: 1
        MaxCapacity: 1
