name: Deploy to AWS Copilot

on:
  push:
    branches:
      - dev
      #- staging
      #- master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Deployment environment based on branch
        run: |
          echo "GITHUB REF -> ${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "DEPLOY_ENV=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV      
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag,& push docker image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }} # use a unique tag
        run: |
          echo "Building image: mymonorepo-ecr-trial-0 "
          docker build -f dockerfile_nginx -t mymonorepo-ecr-trial-0 .

          echo "Verifying build image..."
          docker images | grep mymonorepo-ecr-trial-0 || echo "image not found!"

          echo "Tag the build image"
          docker tag mymonorepo-ecr-trial-0 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          echo "Verifying tagged build image..."
          docker images | grep $IMAGE_TAG || echo "tagged image not found!"

          echo "Pushing image to ECR... $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 

      - name: Update Copilot Manifest with New Image (to handle the dynamic tagging from the previous step)
        run: |
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          sed -i "s|location: .*|location: \"$IMAGE_URI\"|" copilot/${{ secrets.ECS_SERVICE }}/manifest.yml
          echo "Updated manifest.yml:"
          cat copilot/${{ secrets.ECS_SERVICE }}/manifest.yml  # Debugging   

      - name: Deploy to Amazon Copilot 
        run: |
          curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot-cli
          sudo mv copilot-cli /usr/local/bin/copilot
          echo "Deploying to the following environment: $DEPLOY_ENV"
          copilot svc deploy --name ${{ secrets.ECS_SERVICE }} --env $DEPLOY_ENV \
          --force -- image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG #pass explicit image    
          
      - name: Check ECS to verify images
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_SERVICE }} | grep image   




